# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    trusted_hosts: null
    handle_all_throwables: true
    default_locale: en

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    esi: true
    fragments: true
    php_errors:
        log: true

    ide: null

#            example_api:
#                base_uri: 'https://api.github.com/repos/symfony/symfony-docs'
#                # HTTP Basic authentication
#                auth_basic: 'the-username:the-password'
#                # HTTP Bearer authentication (also called token authentication)
#                auth_bearer: the-bearer-token

    http_client:
        default_options:
            max_redirects: 7
        scoped_clients:
            githubContentClient:
                base_uri: 'https://raw.githubusercontent.com'
#                # HTTP Basic authentication
#                auth_basic: 'the-username:the-password'
#                # HTTP Bearer authentication (also called token authentication)
#                auth_bearer: the-bearer-token
            carApiClient:
                base_uri: 'https://carapi.app'
#                # HTTP Basic authentication
#                auth_basic: 'a1265bb98e84f6e3af509dc667449744'
#                # HTTP Bearer authentication (also called token authentication)
#                auth_bearer: bd01f477-bd7c-4412-ad6f-dd1b22420e4c

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

#when@dev:
#    _errors:
#        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
#        prefix:   /_error
