twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
#        app_version: '%app_version%'
#        locales: '%app_locales%'
#        locale: '%locale%'
        app_version: '%env(APP_VERSION)%'
        app_site_name: '%env(APP_SITE_NAME)%'
        app_site_branding: '%env(APP_SITE_BRANDING)%'
        error: ''


when@dev:
    twig:
        cache: false
        auto_reload: true


when@test:
    twig:
        strict_variables: true
