twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
#        app_version: '%app_version%'
#        locales: '%app_locales%'
#        locale: '%locale%'
        app_version: '%env(APP_VERSION)%'
        error: ''
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

when@dev:
    twig:
        cache: false
        auto_reload: true


when@test:
    twig:
        strict_variables: true
