<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230526051149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add specs filed into product table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE `product` ADD `vin` text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD `year` text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD make text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD model text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD trim text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD suggested_vin text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD possible_values text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD vehicle_descriptor text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD destination_market text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD manufacturer_name text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD plant_city text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD series text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD vehicle_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD plant_country text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD plant_company_name text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD plant_state text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD trim2 text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD series2 text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD note text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD base_price text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD non_land_use text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD body_class text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD doors text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD `windows` text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD wheel_base_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD track_width_inches text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD gross_vehicle_weight_rating_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD bed_length_inches text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD curb_weight_pounds text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD wheel_base_inches_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD wheel_base_inches_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD gross_combination_weight_rating_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD gross_combination_weight_rating_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD gross_vehicle_weight_rating_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD bed_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD cab_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD trailer_type_connection text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD trailer_body_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD trailer_length_feet text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD other_trailer_info text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD number_of_wheels text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD wheel_size_front_inches text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD wheel_size_rear_inches text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD entertainment_system text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD steering_location text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD number_of_seats INT DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD number_of_seat_rows INT DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD transmission_style text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD transmission_speeds text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD drive_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD axles text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD axle_configuration text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD brake_system_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD brake_system_description text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD other_battery_info text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD number_of_battery_cells_per_module text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_current_amps_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_voltage_volts_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_energy_kwh_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD ev_drive_unit text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_current_amps_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_voltage_volts_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD battery_energy_kwh_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD number_of_battery_modules_per_pack text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD number_of_battery_packs_per_vehicle text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD charger_level text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD charger_power_kw text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_number_of_cylinders INT DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD displacement_cc DECIMAL(10,2) DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD displacement_ci DECIMAL(10,2) DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD displacement_l DECIMAL(10,2) DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_stroke_cycles text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_model text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_power_kw DECIMAL(10,2) DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD fuel_type_primary text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD valve_train_design text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_configuration text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD fuel_type_secondary text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD fuel_delivery_fuel_injection_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_brake_hp_from INT DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD cooling_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_brake_hp_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD electrification_level text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD other_engine_info text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD turbo text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD top_speed_mph text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD engine_manufacturer text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD pretensioner text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD seat_belt_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD other_restraint_system_info text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD curtain_air_bag_locations text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD seat_cushion_air_bag_locations text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD front_air_bag_locations text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD knee_air_bag_locations text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD side_air_bag_locations text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD anti_lock_braking_system_abs text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD electronic_stability_control_esc text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD traction_control text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD tire_pressure_monitoring_system_tpms_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD active_safety_system_note text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD auto_reverse_system_for_windows_and_sunroofs text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD automatic_pedestrian_alerting_sound_for_hybrid_and_ev_only text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD event_data_recorder_edr text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD keyless_ignition text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD sae_automation_level_from text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD sae_automation_level_to text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD ncsa_body_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD ncsa_make text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD ncsa_model text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD ncsa_note text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD adaptive_cruise_control_acc text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD crash_imminent_braking_cib text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD blind_spot_warning_bsw text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD forward_collision_warning_fcw text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD lane_departure_warning_ldw text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD lane_keeping_assistance_lka text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD backup_camera text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD parking_assist text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD bus_length_feet text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD bus_floor_configuration_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD bus_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD other_bus_info text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD custom_motorcycle_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD motorcycle_suspension_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD motorcycle_chassis_type text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD other_motorcycle_info text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD dynamic_brake_support_dbs text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD pedestrian_automatic_emergency_braking_paeb text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD automatic_and_advanced_crash_notification_aacn text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD daytime_running_light_drl text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD headlamp_light_source text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD semiautomatic_headlamp_beam_switching text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD adaptive_driving_beam_adb text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD rear_cross_traffic_alert text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD rear_automatic_emergency_braking text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD blind_spot_intervention_bsi text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD lane_centering_assistance text DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD `vin_response` JSON NULL DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD `created_at` datetime DATETIME NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE `product` ADD `modified_at` datetime DATETIME NULL DEFAULT CURRENT_TIMESTAMP');

    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE `product` DROP `vin`');
        $this->addSql('ALTER TABLE `product` DROP `year`');
        $this->addSql('ALTER TABLE `product` DROP make');
        $this->addSql('ALTER TABLE `product` DROP model');
        $this->addSql('ALTER TABLE `product` DROP trim');
        $this->addSql('ALTER TABLE `product` DROP suggested_vin');
        $this->addSql('ALTER TABLE `product` DROP possible_values');
        $this->addSql('ALTER TABLE `product` DROP vehicle_descriptor');
        $this->addSql('ALTER TABLE `product` DROP destination_market');
        $this->addSql('ALTER TABLE `product` DROP manufacturer_name');
        $this->addSql('ALTER TABLE `product` DROP plant_city');
        $this->addSql('ALTER TABLE `product` DROP series');
        $this->addSql('ALTER TABLE `product` DROP vehicle_type');
        $this->addSql('ALTER TABLE `product` DROP plant_country');
        $this->addSql('ALTER TABLE `product` DROP plant_company_name');
        $this->addSql('ALTER TABLE `product` DROP plant_state');
        $this->addSql('ALTER TABLE `product` DROP trim2');
        $this->addSql('ALTER TABLE `product` DROP series2');
        $this->addSql('ALTER TABLE `product` DROP note');
        $this->addSql('ALTER TABLE `product` DROP base_price');
        $this->addSql('ALTER TABLE `product` DROP non_land_use');
        $this->addSql('ALTER TABLE `product` DROP body_class');
        $this->addSql('ALTER TABLE `product` DROP doors');
        $this->addSql('ALTER TABLE `product` DROP `windows`');
        $this->addSql('ALTER TABLE `product` DROP wheel_base_type');
        $this->addSql('ALTER TABLE `product` DROP track_width_inches');
        $this->addSql('ALTER TABLE `product` DROP gross_vehicle_weight_rating_from');
        $this->addSql('ALTER TABLE `product` DROP bed_length_inches');
        $this->addSql('ALTER TABLE `product` DROP curb_weight_pounds');
        $this->addSql('ALTER TABLE `product` DROP wheel_base_inches_from');
        $this->addSql('ALTER TABLE `product` DROP wheel_base_inches_to');
        $this->addSql('ALTER TABLE `product` DROP gross_combination_weight_rating_from');
        $this->addSql('ALTER TABLE `product` DROP gross_combination_weight_rating_to');
        $this->addSql('ALTER TABLE `product` DROP gross_vehicle_weight_rating_to');
        $this->addSql('ALTER TABLE `product` DROP bed_type');
        $this->addSql('ALTER TABLE `product` DROP cab_type');
        $this->addSql('ALTER TABLE `product` DROP trailer_type_connection');
        $this->addSql('ALTER TABLE `product` DROP trailer_body_type');
        $this->addSql('ALTER TABLE `product` DROP trailer_length_feet');
        $this->addSql('ALTER TABLE `product` DROP other_trailer_info');
        $this->addSql('ALTER TABLE `product` DROP number_of_wheels');
        $this->addSql('ALTER TABLE `product` DROP wheel_size_front_inches');
        $this->addSql('ALTER TABLE `product` DROP wheel_size_rear_inches');
        $this->addSql('ALTER TABLE `product` DROP entertainment_system');
        $this->addSql('ALTER TABLE `product` DROP steering_location');
        $this->addSql('ALTER TABLE `product` DROP number_of_seats');
        $this->addSql('ALTER TABLE `product` DROP number_of_seat_rows');
        $this->addSql('ALTER TABLE `product` DROP transmission_style');
        $this->addSql('ALTER TABLE `product` DROP transmission_speeds');
        $this->addSql('ALTER TABLE `product` DROP drive_type');
        $this->addSql('ALTER TABLE `product` DROP axles');
        $this->addSql('ALTER TABLE `product` DROP axle_configuration');
        $this->addSql('ALTER TABLE `product` DROP brake_system_type');
        $this->addSql('ALTER TABLE `product` DROP brake_system_description');
        $this->addSql('ALTER TABLE `product` DROP other_battery_info');
        $this->addSql('ALTER TABLE `product` DROP battery_type');
        $this->addSql('ALTER TABLE `product` DROP number_of_battery_cells_per_module');
        $this->addSql('ALTER TABLE `product` DROP battery_current_amps_from');
        $this->addSql('ALTER TABLE `product` DROP battery_voltage_volts_from');
        $this->addSql('ALTER TABLE `product` DROP battery_energy_kwh_from');
        $this->addSql('ALTER TABLE `product` DROP ev_drive_unit');
        $this->addSql('ALTER TABLE `product` DROP battery_current_amps_to');
        $this->addSql('ALTER TABLE `product` DROP battery_voltage_volts_to');
        $this->addSql('ALTER TABLE `product` DROP battery_energy_kwh_to');
        $this->addSql('ALTER TABLE `product` DROP number_of_battery_modules_per_pack');
        $this->addSql('ALTER TABLE `product` DROP number_of_battery_packs_per_vehicle');
        $this->addSql('ALTER TABLE `product` DROP charger_level');
        $this->addSql('ALTER TABLE `product` DROP charger_power_kw');
        $this->addSql('ALTER TABLE `product` DROP engine_number_of_cylinders');
        $this->addSql('ALTER TABLE `product` DROP displacement_cc');
        $this->addSql('ALTER TABLE `product` DROP displacement_ci');
        $this->addSql('ALTER TABLE `product` DROP displacement_l');
        $this->addSql('ALTER TABLE `product` DROP engine_stroke_cycles');
        $this->addSql('ALTER TABLE `product` DROP engine_model');
        $this->addSql('ALTER TABLE `product` DROP engine_power_kw');
        $this->addSql('ALTER TABLE `product` DROP fuel_type_primary');
        $this->addSql('ALTER TABLE `product` DROP valve_train_design');
        $this->addSql('ALTER TABLE `product` DROP engine_configuration');
        $this->addSql('ALTER TABLE `product` DROP fuel_type_secondary');
        $this->addSql('ALTER TABLE `product` DROP fuel_delivery_fuel_injection_type');
        $this->addSql('ALTER TABLE `product` DROP engine_brake_hp_from');
        $this->addSql('ALTER TABLE `product` DROP cooling_type');
        $this->addSql('ALTER TABLE `product` DROP engine_brake_hp_to');
        $this->addSql('ALTER TABLE `product` DROP electrification_level');
        $this->addSql('ALTER TABLE `product` DROP other_engine_info');
        $this->addSql('ALTER TABLE `product` DROP turbo');
        $this->addSql('ALTER TABLE `product` DROP top_speed_mph');
        $this->addSql('ALTER TABLE `product` DROP engine_manufacturer');
        $this->addSql('ALTER TABLE `product` DROP pretensioner');
        $this->addSql('ALTER TABLE `product` DROP seat_belt_type');
        $this->addSql('ALTER TABLE `product` DROP other_restraint_system_info');
        $this->addSql('ALTER TABLE `product` DROP curtain_air_bag_locations');
        $this->addSql('ALTER TABLE `product` DROP seat_cushion_air_bag_locations');
        $this->addSql('ALTER TABLE `product` DROP front_air_bag_locations');
        $this->addSql('ALTER TABLE `product` DROP knee_air_bag_locations');
        $this->addSql('ALTER TABLE `product` DROP side_air_bag_locations');
        $this->addSql('ALTER TABLE `product` DROP anti_lock_braking_system_abs');
        $this->addSql('ALTER TABLE `product` DROP electronic_stability_control_esc');
        $this->addSql('ALTER TABLE `product` DROP traction_control');
        $this->addSql('ALTER TABLE `product` DROP tire_pressure_monitoring_system_tpms_type');
        $this->addSql('ALTER TABLE `product` DROP active_safety_system_note');
        $this->addSql('ALTER TABLE `product` DROP auto_reverse_system_for_windows_and_sunroofs');
        $this->addSql('ALTER TABLE `product` DROP automatic_pedestrian_alerting_sound_for_hybrid_and_ev_only');
        $this->addSql('ALTER TABLE `product` DROP event_data_recorder_edr');
        $this->addSql('ALTER TABLE `product` DROP keyless_ignition');
        $this->addSql('ALTER TABLE `product` DROP sae_automation_level_from');
        $this->addSql('ALTER TABLE `product` DROP sae_automation_level_to');
        $this->addSql('ALTER TABLE `product` DROP ncsa_body_type');
        $this->addSql('ALTER TABLE `product` DROP ncsa_make');
        $this->addSql('ALTER TABLE `product` DROP ncsa_model');
        $this->addSql('ALTER TABLE `product` DROP ncsa_note');
        $this->addSql('ALTER TABLE `product` DROP adaptive_cruise_control_acc');
        $this->addSql('ALTER TABLE `product` DROP crash_imminent_braking_cib');
        $this->addSql('ALTER TABLE `product` DROP blind_spot_warning_bsw');
        $this->addSql('ALTER TABLE `product` DROP forward_collision_warning_fcw');
        $this->addSql('ALTER TABLE `product` DROP lane_departure_warning_ldw');
        $this->addSql('ALTER TABLE `product` DROP lane_keeping_assistance_lka');
        $this->addSql('ALTER TABLE `product` DROP backup_camera');
        $this->addSql('ALTER TABLE `product` DROP parking_assist');
        $this->addSql('ALTER TABLE `product` DROP bus_length_feet');
        $this->addSql('ALTER TABLE `product` DROP bus_floor_configuration_type');
        $this->addSql('ALTER TABLE `product` DROP bus_type');
        $this->addSql('ALTER TABLE `product` DROP other_bus_info');
        $this->addSql('ALTER TABLE `product` DROP custom_motorcycle_type');
        $this->addSql('ALTER TABLE `product` DROP motorcycle_suspension_type');
        $this->addSql('ALTER TABLE `product` DROP motorcycle_chassis_type');
        $this->addSql('ALTER TABLE `product` DROP other_motorcycle_info');
        $this->addSql('ALTER TABLE `product` DROP dynamic_brake_support_dbs');
        $this->addSql('ALTER TABLE `product` DROP pedestrian_automatic_emergency_braking_paeb');
        $this->addSql('ALTER TABLE `product` DROP automatic_and_advanced_crash_notification_aacn');
        $this->addSql('ALTER TABLE `product` DROP daytime_running_light_drl');
        $this->addSql('ALTER TABLE `product` DROP headlamp_light_source');
        $this->addSql('ALTER TABLE `product` DROP semiautomatic_headlamp_beam_switching');
        $this->addSql('ALTER TABLE `product` DROP adaptive_driving_beam_adb');
        $this->addSql('ALTER TABLE `product` DROP rear_cross_traffic_alert');
        $this->addSql('ALTER TABLE `product` DROP rear_automatic_emergency_braking');
        $this->addSql('ALTER TABLE `product` DROP blind_spot_intervention_bsi');
        $this->addSql('ALTER TABLE `product` DROP lane_centering_assistance');
        $this->addSql('ALTER TABLE `product` ADD `vin_response` JSON NULL DEFAULT NULL');
        $this->addSql('ALTER TABLE `product` ADD `created_at` datetime DATETIME NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE `product` ADD `modified_at` datetime DATETIME NULL DEFAULT CURRENT_TIMESTAMP');

    }
}
