default_route:
    path: /
#    controller: App\Controller\PropertyController::search
#    defaults:
#      path: /en
#      permanent: true
    controller: App\Controller\DashController::index
    defaults:
      path: /en
      permanent: true




sub_categories:
  path: /sub_categories/{category_id}
  controller: App\Controller\ProductController::fetchSubcategories
  methods: ["GET"]